<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ContactRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'name' => 'required|max:30',
            'email' => 'required|email',
            'subject' => 'required|min:5|max:20',
            'message' => 'required|max:50'
        ];
    }

    //Переобпеделяем название поля формы
    public function  attributes()
    {
        return [
            'name' => 'имя'
        ]; // TODO: Change the autogenerated stub
    }

    public function messages(){
        return [
            'name.required' => 'Поле "Имя" является обязательным',
            'email.required' => 'Поле "Адрес электронной почты" является обязательным',
            'email.email' => 'Поле "Адрес электронной почты" не коррктно',
            'subject.required' => 'Поле "Тема сообщения" является обязательным',
            'subject.min' => 'Поле "Тема сообщения" не может быть короче 3 символов',
            'subject.max' => 'Поле "Тема сообщения" не может быть больше 20 символов',
            'message.required' => 'Поле "Сообщение" является обязательным',
            'message.max' => 'Поле "Сообщение" не может быть больше 50 символов',
        ];
    }
}
